import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export async function seedBrandProducts() {
  console.log("🚀 Seeding Official Brand Products for all 16 Brands...");

  // 1. Categories Definition
  const categoriesData = [
    { name: "Laptop", slug: "laptops", iconName: "Laptop", description: "Gaming, Ultrabooks, Business & Student Laptops", order: 1, imageUrl: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=400&auto=format&fit=crop&q=80" },
    { name: "Mobile", slug: "mobiles", iconName: "Smartphone", description: "5G Smartphones, Flagships, Gaming Phones & Tablets", order: 2, imageUrl: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=400&auto=format&fit=crop&q=80" },
    { name: "Printer", slug: "printers", iconName: "Printer", description: "Ink Tank, Laser, All-in-One Wireless Printers & Scanners", order: 3, imageUrl: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=400&auto=format&fit=crop&q=80" },
    { name: "CCTV Camera", slug: "cctv-camera", iconName: "Camera", description: "HD IP Cameras, ColorVu Night Vision, WiFi PTZ & NVRs", order: 4, imageUrl: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=400&auto=format&fit=crop&q=80" },
    { name: "Custom Gaming PCs", slug: "custom-gaming-pcs", iconName: "Cpu", description: "Extreme Performance custom liquid-cooled RGB Battle-stations", order: 5, imageUrl: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=400&auto=format&fit=crop&q=80" },
    { name: "Desktop PC", slug: "desktops", iconName: "Monitor", description: "All-in-One and Tower Desktop Computers", order: 6, imageUrl: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400&auto=format&fit=crop&q=80" },
    { name: "Processors (CPU)", slug: "processors", iconName: "Cpu", description: "Intel Core & AMD Ryzen processors", order: 7, imageUrl: "https://images.unsplash.com/photo-1555618568-9a3d4608c0ff?w=400&auto=format&fit=crop&q=80" },
    { name: "Graphics Cards (GPU)", slug: "graphics-cards", iconName: "Tv", description: "NVIDIA GeForce RTX & AMD Radeon RX series", order: 8, imageUrl: "https://images.unsplash.com/photo-1591488320449-011701bb6704?w=400&auto=format&fit=crop&q=80" },
    { name: "RAM & Memory", slug: "ram", iconName: "Cpu", description: "DDR4 and DDR5 Gaming & Desktop RAM", order: 9, imageUrl: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=400&auto=format&fit=crop&q=80" },
    { name: "Storage (SSD / HDD)", slug: "storage", iconName: "Database", description: "NVMe M.2 Gen4 SSDs & High Capacity Hard Drives", order: 10, imageUrl: "https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=400&auto=format&fit=crop&q=80" },
    { name: "Monitors", slug: "monitors", iconName: "Monitor", description: "Gaming and Professional IPS Monitors", order: 11, imageUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&auto=format&fit=crop&q=80" },
    { name: "Accessories", slug: "accessories", iconName: "Headphones", description: "Mechanical Keyboards, Wireless Mice & Accessories", order: 12, imageUrl: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=400&auto=format&fit=crop&q=80" },
  ];

  const categoryMap = new Map<string, string>();
  for (const c of categoriesData) {
    const cat = await prisma.category.upsert({
      where: { slug: c.slug },
      update: { name: c.name, order: c.order, description: c.description, iconName: c.iconName, imageUrl: c.imageUrl },
      create: c,
    });
    categoryMap.set(c.slug, cat.id);
    categoryMap.set(c.name.toLowerCase(), cat.id);
  }

  // 2. All 16 Official Brands
  const brandsData = [
    { name: "AMD", slug: "amd" },
    { name: "Apple", slug: "apple" },
    { name: "ASUS", slug: "asus" },
    { name: "Corsair", slug: "corsair" },
    { name: "CP PLUS", slug: "cp-plus" },
    { name: "Dell", slug: "dell" },
    { name: "Epson", slug: "epson" },
    { name: "Google", slug: "google" },
    { name: "HP", slug: "hp" },
    { name: "Intel", slug: "intel" },
    { name: "Lenovo", slug: "lenovo" },
    { name: "Logitech", slug: "logitech" },
    { name: "MSI", slug: "msi" },
    { name: "NVIDIA", slug: "nvidia" },
    { name: "OnePlus", slug: "oneplus" },
    { name: "Samsung", slug: "samsung" },
  ];

  const brandMap = new Map<string, string>();
  for (const b of brandsData) {
    const brand = await prisma.brand.upsert({
      where: { slug: b.slug },
      update: { name: b.name, isActive: true },
      create: { name: b.name, slug: b.slug, isActive: true },
    });
    brandMap.set(b.slug, brand.id);
  }

  // 3. Products for every brand
  const products = [
    // --- 1. AMD ---
    {
      name: "AMD Ryzen 7 7800X3D Desktop Processor (8 Cores / 16 Threads, 3D V-Cache)",
      slug: "amd-ryzen-7-7800x3d-desktop-processor",
      sku: "JC-AMD-7800X3D",
      categorySlug: "processors",
      brandSlug: "amd",
      price: 44990,
      salePrice: 38990,
      stock: 12,
      warranty: "3 Years AMD India Brand Warranty",
      shortDesc: "The undisputed king of gaming CPUs. 8 Cores, 16 Threads, 104MB Cache, 5.0 GHz Max Boost, AM5 Platform.",
      description: "Equipped with AMD 3D V-Cache technology, the Ryzen 7 7800X3D delivers incredible high-FPS smoothness in competitive gaming titles and simulations.",
      imageUrl: "https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=800&auto=format&fit=crop&q=80",
      isFeatured: true,
      isBestseller: true,
      isGamingDeal: true,
      isNewArrival: true,
      specs: JSON.stringify({ "Socket": "AM5", "Cores / Threads": "8 / 16", "Base Clock": "4.2 GHz", "Boost Clock": "Up to 5.0 GHz", "Total Cache": "104 MB", "TDP": "120W" }),
    },
    {
      name: "AMD Ryzen 5 7600X Desktop Processor (6 Cores / 12 Threads)",
      slug: "amd-ryzen-5-7600x-desktop-processor",
      sku: "JC-AMD-7600X",
      categorySlug: "processors",
      brandSlug: "amd",
      price: 24990,
      salePrice: 20490,
      stock: 15,
      warranty: "3 Years AMD India Warranty",
      shortDesc: "Next-gen Zen 4 performance for mid-range gaming builds. Up to 5.3 GHz boost, DDR5 & PCIe 5.0 ready.",
      description: "Dominate your games and creative workflows with 6 high-speed Zen 4 cores built on energy-efficient 5nm architecture.",
      imageUrl: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&auto=format&fit=crop&q=80",
      isFeatured: false,
      isBestseller: false,
      isGamingDeal: true,
      isNewArrival: false,
      specs: JSON.stringify({ "Socket": "AM5", "Cores": "6", "Threads": "12", "Boost Clock": "5.3 GHz", "Cache": "38 MB", "TDP": "105W" }),
    },

    // --- 2. APPLE ---
    {
      name: "Apple MacBook Air 13.6-inch (M3 Chip, 16GB RAM, 512GB SSD)",
      slug: "apple-macbook-air-m3-16gb-512gb",
      sku: "JC-MAC-M3-01",
      categorySlug: "laptops",
      brandSlug: "apple",
      price: 134900,
      salePrice: 124900,
      stock: 8,
      warranty: "1 Year Apple India Official Warranty",
      shortDesc: "M3 chip with 8-core CPU, 10-core GPU, Liquid Retina display, 18-hour battery life, Midnight Black.",
      description: "Supercharged by the next-generation M3 chip, the redesigned MacBook Air combines incredible performance and up to 18 hours of battery life into a strikingly thin aluminum enclosure.",
      imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80",
      isFeatured: true,
      isBestseller: true,
      isGamingDeal: false,
      isNewArrival: true,
      specs: JSON.stringify({ "Processor": "Apple M3 (8-core CPU / 10-core GPU)", "RAM": "16GB Unified Memory", "Storage": "512GB NVMe SSD", "Display": "13.6-inch Liquid Retina", "Battery": "Up to 18 hours" }),
    },
    {
      name: "Apple iPhone 15 Pro (128GB, Natural Titanium)",
      slug: "apple-iphone-15-pro-128gb",
      sku: "JC-IPH-15P-01",
      categorySlug: "mobiles",
      brandSlug: "apple",
      price: 134900,
      salePrice: 127900,
      stock: 6,
      warranty: "1 Year Apple India Warranty",
      shortDesc: "Aerospace-grade titanium design, A17 Pro chip, Action button, 48MP Main camera with 3x Telephoto.",
      description: "Forged in titanium and featuring the groundbreaking A17 Pro chip, a customizable Action button, and the most powerful iPhone camera system ever.",
      imageUrl: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80",
      isFeatured: true,
      isBestseller: true,
      isGamingDeal: false,
      isNewArrival: true,
      specs: JSON.stringify({ "Display": "6.1-inch Super Retina XDR ProMotion 120Hz", "Chip": "A17 Pro", "Storage": "128GB", "Camera": "48MP + 12MP + 12MP", "Build": "Titanium" }),
    },

    // --- 3. ASUS ---
    {
      name: "ASUS ROG Strix G16 (2024) Gaming Laptop (Core i7-13650HX, RTX 4060, 16GB, 1TB)",
      slug: "asus-rog-strix-g16-2024",
      sku: "JC-ROG-G16-01",
      categorySlug: "laptops",
      brandSlug: "asus",
      price: 154990,
      salePrice: 139990,
      stock: 6,
      warranty: "1 Year ASUS Brand Warranty",
      shortDesc: "Intel Core i7-13650HX, 16GB DDR5, 1TB SSD, NVIDIA GeForce RTX 4060 8GB, 165Hz FHD+ Display.",
      description: "Dominate the competition with the ROG Strix G16 featuring high-power Intel Core processors and NVIDIA RTX 40-Series graphics cooled by ROG Intelligent Cooling with Conductonaut Extreme liquid metal.",
      imageUrl: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&auto=format&fit=crop&q=80",
      isFeatured: true,
      isBestseller: true,
      isGamingDeal: true,
      isNewArrival: true,
      specs: JSON.stringify({ "CPU": "Intel Core i7-13650HX", "GPU": "NVIDIA GeForce RTX 4060 8GB (140W TGP)", "RAM": "16GB DDR5 4800MHz", "Storage": "1TB PCIe 4.0 SSD", "Display": "16-inch 165Hz 100% sRGB" }),
    },
    {
      name: "ASUS ROG Swift OLED PG27AQDM 27-inch 240Hz Gaming Monitor",
      slug: "asus-rog-swift-oled-pg27aqdm-240hz",
      sku: "JC-MON-OLED-240",
      categorySlug: "monitors",
      brandSlug: "asus",
      price: 99990,
      salePrice: 89990,
      stock: 4,
      warranty: "3 Years ASUS Warranty with OLED Care",
      shortDesc: "27-inch QHD (2560 x 1440) OLED, 240Hz, 0.03ms Response Time, 99% DCI-P3, Custom Heatsink.",
      description: "Unrivaled OLED visuals with lightning 0.03ms response time, deep inky blacks, and custom heatsink design to prevent burn-in.",
      imageUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80",
      isFeatured: false,
      isBestseller: false,
      isGamingDeal: true,
      isNewArrival: false,
      specs: JSON.stringify({ "Panel": "OLED 27-inch QHD", "Refresh Rate": "240Hz", "Response Time": "0.03ms (GTG)", "Color Gamut": "99% DCI-P3", "HDR": "HDR10" }),
    },

    // --- 4. CORSAIR ---
    {
      name: "Corsair Vengeance RGB 32GB (2x16GB) DDR5 6000MHz CL30 RAM Kit",
      slug: "corsair-vengeance-rgb-32gb-ddr5",
      sku: "JC-RAM-DDR5-32",
      categorySlug: "ram",
      brandSlug: "corsair",
      price: 12490,
      salePrice: 10490,
      stock: 20,
      warranty: "10 Years / Lifetime Limited Warranty",
      shortDesc: "DDR5 6000MHz CL30, Intel XMP 3.0 & AMD EXPO Compatible, Ten-Zone RGB Lighting, Black Heatspreader.",
      description: "Deliver higher frequencies and greater capacities of DDR5 technology in a compact module with dynamic ten-zone RGB lighting and onboard voltage regulation for fine-tuned overclocking.",
      imageUrl: "https://images.unsplash.com/photo-1562976540-1502c2145186?w=800&auto=format&fit=crop&q=80",
      isFeatured: false,
      isBestseller: true,
      isGamingDeal: true,
      isNewArrival: false,
      specs: JSON.stringify({ "Memory Size": "32GB (2 x 16GB)", "Speed": "DDR5-6000MHz", "Latency": "CL30-36-36-76", "Voltage": "1.35V", "Profiles": "Intel XMP 3.0 & AMD EXPO" }),
    },
    {
      name: "Corsair RM850e 850W 80+ Gold Fully Modular ATX 3.0 Power Supply",
      slug: "corsair-rm850e-850w-gold-power-supply",
      sku: "JC-PSU-RM850E",
      categorySlug: "accessories",
      brandSlug: "corsair",
      price: 13990,
      salePrice: 11490,
      stock: 14,
      warranty: "7 Years Corsair Brand Warranty",
      shortDesc: "80 PLUS Gold Certified, PCIe 5.0 12VHPWR Native Cable, 120mm Rifle Bearing Fan, 105C Capacitors.",
      description: "Quiet, reliable power with 80 PLUS Gold efficiency, fully modular cables, and native ATX 3.0 & PCIe 5.0 compliance for latest RTX 40-Series GPUs.",
      imageUrl: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&auto=format&fit=crop&q=80",
      isFeatured: false,
      isBestseller: false,
      isGamingDeal: false,
      isNewArrival: false,
      specs: JSON.stringify({ "Wattage": "850W", "Efficiency": "80 PLUS Gold", "Modularity": "Full Modular", "Standard": "ATX 3.0 / PCIe 5.0 12VHPWR", "Warranty": "7 Years" }),
    },

    // --- 5. CP PLUS ---
    {
      name: "CP PLUS 4MP Guard+ Smart Wi-Fi PT CCTV Security Camera (360° Pan-Tilt)",
      slug: "cp-plus-4mp-guard-plus-smart-wifi-cctv",
      sku: "JC-CCTV-4MP-CP",
      categorySlug: "cctv-camera",
      brandSlug: "cp-plus",
      price: 3999,
      salePrice: 2499,
      stock: 25,
      warranty: "2 Years CP PLUS Brand Warranty",
      shortDesc: "4MP Ultra HD, 360-degree Pan/Tilt, Full Color Night Vision, Two-Way Audio, Motion Tracking.",
      description: "Protect your home, shop, or office with 360-degree coverage, crystal-clear 4MP resolution, AI human detection, and instant phone alerts on the CP PLUS mobile app.",
      imageUrl: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&auto=format&fit=crop&q=80",
      isFeatured: true,
      isBestseller: true,
      isGamingDeal: false,
      isNewArrival: false,
      specs: JSON.stringify({ "Resolution": "4MP (2560 x 1440)", "Rotation": "360° Pan, 90° Tilt", "Night Vision": "Full Color Smart Night Vision", "Audio": "2-Way Talkback", "Storage": "MicroSD Up to 256GB / Cloud" }),
    },
    {
      name: "CP PLUS 8-Channel 5MP HD DVR Surveillance Kit (with 4 Night Vision Cameras)",
      slug: "cp-plus-8-channel-5mp-dvr-cctv-kit",
      sku: "JC-CCTV-8CH-KIT",
      categorySlug: "cctv-camera",
      brandSlug: "cp-plus",
      price: 18990,
      salePrice: 14490,
      stock: 10,
      warranty: "2 Years CP PLUS Onsite Warranty",
      shortDesc: "Complete shop/farm surveillance kit: 8-CH 5MP DVR, 2 Bullet + 2 Dome Cameras, 1TB Surveillance HDD, Cables & SMPS.",
      description: "Heavy-duty outdoor and indoor security package. All-weather waterproof IP66 casing with 30m infrared illumination and remote mobile monitoring.",
      imageUrl: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&auto=format&fit=crop&q=80",
      isFeatured: false,
      isBestseller: true,
      isGamingDeal: false,
      isNewArrival: true,
      specs: JSON.stringify({ "DVR Channels": "8-Channel 5MP Support", "Cameras Included": "4x 5MP IR Cameras", "Storage": "1TB Surveillance Grade HDD", "Casing": "IP66 Weatherproof", "Warranty": "2 Years" }),
    },

    // --- 6. DELL ---
    {
      name: "Dell Inspiron 15 (Core i5 13th Gen, 16GB RAM, 512GB SSD, 120Hz Display)",
      slug: "dell-inspiron-15-core-i5-13th-gen",
      sku: "JC-DELL-INSP-01",
      categorySlug: "laptops",
      brandSlug: "dell",
      price: 64990,
      salePrice: 54990,
      stock: 12,
      warranty: "1 Year Dell Onsite Domestic Warranty",
      shortDesc: "13th Gen Intel Core i5-1335U, 15.6-inch FHD 120Hz Anti-Glare, Backlit Keyboard, Platinum Silver.",
      description: "Experience responsive yet quiet performance featuring 13th Generation Intel Core processors combined with PCIe SSD options and Dell ComfortView Low Blue Light software.",
      imageUrl: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80",
      isFeatured: true,
      isBestseller: true,
      isGamingDeal: false,
      isNewArrival: false,
      specs: JSON.stringify({ "Processor": "Intel Core i5-1335U (10 Cores, up to 4.60 GHz)", "RAM": "16GB DDR4 3200MHz", "Storage": "512GB M.2 PCIe NVMe SSD", "Display": "15.6-inch FHD (1920x1080) 120Hz", "OS": "Windows 11 Home + MS Office 2021" }),
    },
    {
      name: "Dell Alienware M16 R2 Gaming Laptop (Intel Core Ultra 7, RTX 4070 8GB, 240Hz QHD+)",
      slug: "dell-alienware-m16-r2-gaming-laptop",
      sku: "JC-DELL-AW-M16",
      categorySlug: "laptops",
      brandSlug: "dell",
      price: 219990,
      salePrice: 198990,
      stock: 3,
      warranty: "1 Year Dell Alienware Premium Support",
      shortDesc: "Intel Core Ultra 7 155H, RTX 4070 8GB, 32GB DDR5, 1TB SSD, 240Hz QHD+ 100% DCI-P3 Display.",
      description: "Redesigned Alienware stealth mode gaming laptop powered by Intel Core Ultra AI processing and Alienware Cryo-tech cooling architecture.",
      imageUrl: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&auto=format&fit=crop&q=80",
      isFeatured: false,
      isBestseller: false,
      isGamingDeal: true,
      isNewArrival: true,
      specs: JSON.stringify({ "Processor": "Intel Core Ultra 7 155H", "Graphics": "NVIDIA RTX 4070 8GB GDDR6", "RAM": "32GB DDR5 5600MHz", "Storage": "1TB NVMe PCIe 4.0 SSD", "Display": "16-inch QHD+ 240Hz" }),
    },

    // --- 7. EPSON ---
    {
      name: "Epson EcoTank L3250 Wi-Fi All-in-One Color Ink Tank Printer",
      slug: "epson-ecotank-l3250-wifi-printer",
      sku: "JC-PRN-L3250",
      categorySlug: "printers",
      brandSlug: "epson",
      price: 16999,
      salePrice: 13999,
      stock: 12,
      warranty: "1 Year / 30,000 Pages Epson Onsite Warranty",
      shortDesc: "Print, Scan, Copy, Wi-Fi & Wi-Fi Direct, Ultra-low-cost printing (7 paise per page).",
      description: "Designed to improve business cost savings and print productivity with high page yield of up to 4,500 pages for black and 7,500 pages for color with spill-free refill bottles.",
      imageUrl: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=800&auto=format&fit=crop&q=80",
      isFeatured: true,
      isBestseller: true,
      isGamingDeal: false,
      isNewArrival: false,
      specs: JSON.stringify({ "Functions": "Print, Scan, Copy", "Connectivity": "Wi-Fi, Wi-Fi Direct, USB 2.0", "Cost Per Page": "7 Paise (B/W), 18 Paise (Color)", "Page Yield": "4,500 Black / 7,500 Color", "Print Speed": "33 ppm (Black), 15 ppm (Color)" }),
    },
    {
      name: "Epson EcoTank L6270 Wi-Fi Duplex All-in-One Ink Tank Printer with ADF",
      slug: "epson-ecotank-l6270-duplex-printer",
      sku: "JC-PRN-L6270",
      categorySlug: "printers",
      brandSlug: "epson",
      price: 28999,
      salePrice: 24999,
      stock: 6,
      warranty: "2 Years / 50,000 Pages Epson Warranty",
      shortDesc: "Auto-Duplex (2-sided) printing, 30-sheet Automatic Document Feeder (ADF), Ethernet & PrecisionCore Printhead.",
      description: "High-speed business powerhouse with automatic double-sided printing, ADF for bulk scanning, and smudge-resistant pigment black inks.",
      imageUrl: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=800&auto=format&fit=crop&q=80",
      isFeatured: false,
      isBestseller: false,
      isGamingDeal: false,
      isNewArrival: true,
      specs: JSON.stringify({ "Special Features": "Auto-Duplex Printing, 30-page ADF", "Printhead": "PrecisionCore Heat-Free", "Network": "Wi-Fi, Wi-Fi Direct, Ethernet", "Display": "1.44-inch Color LCD" }),
    },

    // --- 8. GOOGLE ---
    {
      name: "Google Pixel 8 Pro 5G (12GB RAM, 128GB, Obsidian Black)",
      slug: "google-pixel-8-pro-5g-128gb",
      sku: "JC-PIX-8P-01",
      categorySlug: "mobiles",
      brandSlug: "google",
      price: 106999,
      salePrice: 97999,
      stock: 5,
      warranty: "1 Year Google India Warranty",
      shortDesc: "Google Tensor G3, Super Actua display, Pro triple camera with Best Take & Magic Editor.",
      description: "Pixel 8 Pro is the all-pro phone engineered by Google. It has the best Pixel Camera yet, all-day battery, and incredible Google AI features with 7 years of OS updates.",
      imageUrl: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&auto=format&fit=crop&q=80",
      isFeatured: false,
      isBestseller: false,
      isGamingDeal: false,
      isNewArrival: true,
      specs: JSON.stringify({ "Processor": "Google Tensor G3 + Titan M2", "Display": "6.7-inch Super Actua LTPO 120Hz", "RAM / Storage": "12GB LPDDR5X / 128GB UFS 3.1", "Cameras": "50MP Main + 48MP Ultrawide + 48MP 5x Telephoto", "Updates": "7 Years Android OS Support" }),
    },
    {
      name: "Google Pixel 8a 5G (8GB RAM, 128GB, Bay Blue)",
      slug: "google-pixel-8a-5g-128gb",
      sku: "JC-PIX-8A-01",
      categorySlug: "mobiles",
      brandSlug: "google",
      price: 52999,
      salePrice: 47999,
      stock: 8,
      warranty: "1 Year Google India Warranty",
      shortDesc: "Google Tensor G3, 120Hz Actua OLED display, AI photography with Audio Magic Eraser & Circle to Search.",
      description: "The AI-packed phone that delivers flagship Pixel camera quality, all-day battery, and IP67 water resistance at an accessible price.",
      imageUrl: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&auto=format&fit=crop&q=80",
      isFeatured: false,
      isBestseller: true,
      isGamingDeal: false,
      isNewArrival: true,
      specs: JSON.stringify({ "Display": "6.1-inch Actua OLED 120Hz", "Processor": "Google Tensor G3", "RAM": "8GB", "Storage": "128GB", "Camera": "64MP Quad PD + 13MP Ultrawide" }),
    },

    // --- 9. HP ---
    {
      name: "HP Pavilion 15 (13th Gen Intel Core i5, 16GB RAM, 512GB SSD, B&O Audio)",
      slug: "hp-pavilion-15-intel-core-i5",
      sku: "JC-HP-PAV-01",
      categorySlug: "laptops",
      brandSlug: "hp",
      price: 69990,
      salePrice: 59990,
      stock: 10,
      warranty: "1 Year HP India Onsite Warranty",
      shortDesc: "Intel Core i5-1335U, 15.6-inch FHD IPS Micro-Edge display, Audio by B&O, Natural Silver.",
      description: "The HP Pavilion 15 Laptop packs more performance into a smaller profile, so you can get more done wherever you go with premium B&O audio and long battery life.",
      imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80",
      isFeatured: true,
      isBestseller: true,
      isGamingDeal: false,
      isNewArrival: false,
      specs: JSON.stringify({ "Processor": "13th Gen Intel Core i5-1335U (up to 4.6 GHz)", "RAM": "16GB DDR4 3200MHz", "Storage": "512GB PCIe NVMe M.2 SSD", "Audio": "Audio by Bang & Olufsen Dual Speakers", "Display": "15.6-inch FHD IPS Anti-glare" }),
    },
    {
      name: "HP LaserJet Pro MFP M126nw Wireless Multi-Function Laser Printer",
      slug: "hp-laserjet-pro-mfp-m126nw-printer",
      sku: "JC-HP-M126NW",
      categorySlug: "printers",
      brandSlug: "hp",
      price: 21990,
      salePrice: 18490,
      stock: 8,
      warranty: "1 Year HP India Commercial Warranty",
      shortDesc: "High-speed monochrome laser printing, scanning, copying, Wi-Fi, Ethernet & HP Smart App printing.",
      description: "Tackle everyday office tasks with an affordable, full-featured MFP. Easily print, copy, and scan with fast output up to 20 ppm and crisp black text.",
      imageUrl: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=800&auto=format&fit=crop&q=80",
      isFeatured: false,
      isBestseller: true,
      isGamingDeal: false,
      isNewArrival: false,
      specs: JSON.stringify({ "Technology": "Monochrome Laser", "Speed": "Up to 20 ppm", "Connectivity": "Wi-Fi 802.11b/g/n, Fast Ethernet, USB 2.0", "Duty Cycle": "Up to 8,000 pages per month" }),
    },

    // --- 10. INTEL ---
    {
      name: "Intel Core i7-14700K Desktop Processor (20 Cores / 28 Threads, Up to 5.6 GHz)",
      slug: "intel-core-i7-14700k-desktop-processor",
      sku: "JC-CPU-14700K",
      categorySlug: "processors",
      brandSlug: "intel",
      price: 39990,
      salePrice: 36490,
      stock: 15,
      warranty: "3 Years Intel Brand Warranty",
      shortDesc: "20 Cores (8 P-cores + 12 E-cores), Up to 5.6 GHz, LGA1700 Socket, PCIe 5.0 & DDR5 Support.",
      description: "14th Gen Intel Core i7 desktop processor designed for demanding creators, video editors, and high-FPS gaming enthusiasts.",
      imageUrl: "https://images.unsplash.com/photo-1555618568-9a3d4608c0ff?w=800&auto=format&fit=crop&q=80",
      isFeatured: false,
      isBestseller: true,
      isGamingDeal: true,
      isNewArrival: true,
      specs: JSON.stringify({ "Socket": "LGA1700", "Total Cores": "20 (8 Performance + 12 Efficient)", "Total Threads": "28", "Max Turbo": "5.60 GHz", "Intel Smart Cache": "33 MB", "Memory": "DDR5-5600 & DDR4-3200" }),
    },
    {
      name: "Intel Core i5-14400F Desktop Processor (10 Cores / 16 Threads)",
      slug: "intel-core-i5-14400f-desktop-processor",
      sku: "JC-CPU-14400F",
      categorySlug: "processors",
      brandSlug: "intel",
      price: 19990,
      salePrice: 16990,
      stock: 18,
      warranty: "3 Years Intel Brand Warranty with Cooler",
      shortDesc: "10 Cores (6 P-cores + 4 E-cores), Up to 4.7 GHz, Intel Laminar RM1 Cooler Included.",
      description: "Best budget value gaming CPU. Exceptional multi-tasking and gaming performance for mainstream PC builds.",
      imageUrl: "https://images.unsplash.com/photo-1555618568-9a3d4608c0ff?w=800&auto=format&fit=crop&q=80",
      isFeatured: false,
      isBestseller: true,
      isGamingDeal: false,
      isNewArrival: false,
      specs: JSON.stringify({ "Socket": "LGA1700", "Cores": "10 (6P + 4E)", "Threads": "16", "Max Turbo": "4.70 GHz", "Included Cooler": "Intel Laminar RM1", "TDP": "65W" }),
    },

    // --- 11. LENOVO ---
    {
      name: "Lenovo Legion Pro 5i Gen 9 Gaming Laptop (Core i7-14650HX, RTX 4070 8GB, 240Hz WQXGA)",
      slug: "lenovo-legion-pro-5i-gen-9",
      sku: "JC-LEN-LEG-01",
      categorySlug: "laptops",
      brandSlug: "lenovo",
      price: 172990,
      salePrice: 156990,
      stock: 5,
      warranty: "1 Year Lenovo Legion Ultimate Support",
      shortDesc: "Intel Core i7-14650HX, 16GB DDR5, 1TB SSD, RTX 4070 8GB (140W), 240Hz WQXGA 500 nits HDR Display.",
      description: "Engineered for elite competitive gamers, Legion Pro 5i features AI-tuned performance with Legion ColdFront 5.0 cooling technology and pure sRGB color accuracy.",
      imageUrl: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&auto=format&fit=crop&q=80",
      isFeatured: true,
      isBestseller: false,
      isGamingDeal: true,
      isNewArrival: false,
      specs: JSON.stringify({ "CPU": "Intel Core i7-14650HX", "GPU": "NVIDIA GeForce RTX 4070 8GB GDDR6 (140W)", "RAM": "16GB DDR5 5600MHz", "Display": "16-inch WQXGA (2560x1600) 240Hz 500nits 100% sRGB", "Cooling": "Legion Coldfront 5.0" }),
    },
    {
      name: "Lenovo IdeaPad Slim 3 15-inch (Core i5 13th Gen, 16GB RAM, 512GB SSD, Arctic Grey)",
      slug: "lenovo-ideapad-slim-3-core-i5",
      sku: "JC-LEN-SLIM-01",
      categorySlug: "laptops",
      brandSlug: "lenovo",
      price: 59990,
      salePrice: 49990,
      stock: 14,
      warranty: "2 Years Lenovo Warranty + 1 Year ADP",
      shortDesc: "Military Grade Durability (MIL-STD-810H), 15.6-inch FHD Anti-glare, Privacy Shutter Camera, Rapid Charge.",
      description: "Slim, lightweight and built to military toughness standards for students and working professionals on the go.",
      imageUrl: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80",
      isFeatured: false,
      isBestseller: true,
      isGamingDeal: false,
      isNewArrival: false,
      specs: JSON.stringify({ "CPU": "13th Gen Intel Core i5-13420H", "RAM": "16GB LPDDR5", "Storage": "512GB SSD M.2 PCIe 4.0", "Weight": "1.62 kg", "Battery": "Up to 8 hours (Rapid Charge)" }),
    },

    // --- 12. LOGITECH ---
    {
      name: "Logitech G502 X PLUS Wireless RGB Gaming Mouse (HERO 25K Sensor, LIGHTFORCE Switches)",
      slug: "logitech-g502-x-plus-wireless",
      sku: "JC-ACC-G502X",
      categorySlug: "accessories",
      brandSlug: "logitech",
      price: 15495,
      salePrice: 12995,
      stock: 18,
      warranty: "2 Years Logitech Brand Warranty",
      shortDesc: "LIGHTFORCE Hybrid Switches, HERO 25K Sensor, LIGHTSPEED Wireless, LIGHTSYNC 8-Zone RGB.",
      description: "The world's most popular gaming mouse, reimagined and redesigned with hybrid optical-mechanical switches for speed and reliability, adjustable DPI shift button, and dual-mode scroll wheel.",
      imageUrl: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80",
      isFeatured: true,
      isBestseller: true,
      isGamingDeal: true,
      isNewArrival: false,
      specs: JSON.stringify({ "Sensor": "HERO 25K (100 – 25,600 DPI)", "Switches": "LIGHTFORCE Optical-Mechanical", "Battery Life": "Up to 120 hours (RGB off) / 37 hours (RGB on)", "Weight": "106 grams", "Buttons": "13 Programmable" }),
    },
    {
      name: "Logitech MX Master 3S Advanced Wireless Performance Mouse (Quiet Clicks, 8K DPI)",
      slug: "logitech-mx-master-3s-mouse",
      sku: "JC-ACC-MX3S",
      categorySlug: "accessories",
      brandSlug: "logitech",
      price: 10995,
      salePrice: 9495,
      stock: 15,
      warranty: "1 Year Logitech Brand Warranty",
      shortDesc: "MagSpeed Electromagnetic Scrolling, 8,000 DPI Any-Surface Tracking, Quiet Click Tech, Bluetooth & USB-C.",
      description: "An icon remastered for ultimate productivity. Features quiet clicks, 8K DPI glass tracking, and MagSpeed scroll wheel that scrolls 1,000 lines in 1 second.",
      imageUrl: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80",
      isFeatured: false,
      isBestseller: true,
      isGamingDeal: false,
      isNewArrival: true,
      specs: JSON.stringify({ "Sensor": "Darkfield High Precision (8,000 DPI)", "Scroll Wheel": "MagSpeed Electromagnetic", "Multi-Device": "Pair up to 3 computers with Logitech Flow", "Battery": "Up to 70 days per charge" }),
    },

    // --- 13. MSI ---
    {
      name: "MSI GeForce RTX 4070 Super 12GB Gaming X Slim GDDR6X Graphics Card",
      slug: "msi-geforce-rtx-4070-super-12gb",
      sku: "JC-GPU-4070S",
      categorySlug: "graphics-cards",
      brandSlug: "msi",
      price: 68990,
      salePrice: 63990,
      stock: 8,
      warranty: "3 Years MSI Brand Warranty",
      shortDesc: "12GB GDDR6X, DLSS 3.5, Ada Lovelace Architecture, TRI FROZR 3 Thermal Design, RGB Mystic Light.",
      description: "Supercharged gaming and creative performance with full Ray Tracing, AI-accelerated rendering, and ultra-efficient TRI FROZR 3 cooling with TORX Fan 5.0.",
      imageUrl: "https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800&auto=format&fit=crop&q=80",
      isFeatured: true,
      isBestseller: true,
      isGamingDeal: true,
      isNewArrival: false,
      specs: JSON.stringify({ "Memory": "12GB GDDR6X (192-bit)", "CUDA Cores": "7168", "Boost Clock": "2640 MHz", "Power Connectors": "1x 16-pin 12VHPWR", "Display Outputs": "3x DisplayPort 1.4a, 1x HDMI 2.1a" }),
    },
    {
      name: "MSI MAG B650 TOMAHAWK WIFI AM5 Gaming Motherboard",
      slug: "msi-mag-b650-tomahawk-wifi-motherboard",
      sku: "JC-MB-B650-TOM",
      categorySlug: "accessories",
      brandSlug: "msi",
      price: 24990,
      salePrice: 21990,
      stock: 10,
      warranty: "3 Years MSI Brand Warranty",
      shortDesc: "Supports AMD Ryzen 7000/8000/9000 Series, 14+2+1 Duet Rail VRM Power, DDR5 7600+ MHz (OC), Wi-Fi 6E.",
      description: "Built for hardcore gamers with extended heatsink design, M.2 Shield Frozr, lightning PCIe 4.0 M.2 slots, and 2.5G LAN + Wi-Fi 6E.",
      imageUrl: "https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=800&auto=format&fit=crop&q=80",
      isFeatured: false,
      isBestseller: false,
      isGamingDeal: false,
      isNewArrival: true,
      specs: JSON.stringify({ "Socket": "AMD AM5", "VRM": "14+2+1 Phase Direct Power", "RAM Slots": "4x DDR5 Up to 192GB", "Networking": "Wi-Fi 6E + Realtek 2.5G LAN", "Audio": "Realtek ALC4080 Codec" }),
    },

    // --- 14. NVIDIA ---
    {
      name: "NVIDIA GeForce RTX 4080 Super 16GB Founders Edition / Custom Graphics Card",
      slug: "nvidia-geforce-rtx-4080-super-16gb",
      sku: "JC-GPU-4080S",
      categorySlug: "graphics-cards",
      brandSlug: "nvidia",
      price: 108990,
      salePrice: 99990,
      stock: 4,
      warranty: "3 Years Official Warranty",
      shortDesc: "16GB GDDR6X, 10,240 CUDA Cores, 4K High-FPS Ultra Gaming, 3rd Gen RT Cores, 4th Gen Tensor Cores with DLSS 3.5 Frame Gen.",
      description: "Bring your games and creative projects to life with supercharged ray tracing and AI graphics powered by NVIDIA Ada Lovelace architecture and 16GB of blazingly fast G6X memory.",
      imageUrl: "https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800&auto=format&fit=crop&q=80",
      isFeatured: true,
      isBestseller: true,
      isGamingDeal: true,
      isNewArrival: true,
      specs: JSON.stringify({ "VRAM": "16GB GDDR6X (256-bit)", "CUDA Cores": "10,240", "Tensor Cores": "4th Gen AI Acceleration", "Ray Tracing": "3rd Gen RT Cores", "Recommended PSU": "750W / 850W" }),
    },
    {
      name: "NVIDIA GeForce RTX 4060 Ti 8GB Dual-Fan Graphics Card",
      slug: "nvidia-geforce-rtx-4060-ti-8gb",
      sku: "JC-GPU-4060TI",
      categorySlug: "graphics-cards",
      brandSlug: "nvidia",
      price: 43990,
      salePrice: 38990,
      stock: 10,
      warranty: "3 Years Official Warranty",
      shortDesc: "8GB GDDR6, 1080p / 1440p Max Settings Gaming, Full DLSS 3 AI Frame Generation, Low 160W Power Draw.",
      description: "Play latest blockbuster games with high frame rates and full Ray Tracing at 1080p and 1440p with extreme power efficiency.",
      imageUrl: "https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800&auto=format&fit=crop&q=80",
      isFeatured: false,
      isBestseller: true,
      isGamingDeal: true,
      isNewArrival: false,
      specs: JSON.stringify({ "VRAM": "8GB GDDR6 (128-bit)", "CUDA Cores": "4352", "TGP": "160W", "Architecture": "Ada Lovelace", "Outputs": "DisplayPort 1.4a x 3, HDMI 2.1a x 1" }),
    },

    // --- 15. ONEPLUS ---
    {
      name: "OnePlus 12 5G (16GB RAM, 512GB Storage, Silky Black)",
      slug: "oneplus-12-5g-16gb-512gb",
      sku: "JC-OP-12-512",
      categorySlug: "mobiles",
      brandSlug: "oneplus",
      price: 69999,
      salePrice: 64999,
      stock: 7,
      warranty: "1 Year OnePlus India Warranty",
      shortDesc: "Snapdragon 8 Gen 3, 4th Gen Hasselblad Camera, 2K 120Hz ProXDR Display, 100W SUPERVOOC Fast Charging.",
      description: "Experience smooth beyond belief with Snapdragon 8 Gen 3, custom Dual Cryo-velocity VC cooling, and revolutionary 4th Gen Hasselblad Camera System with 64MP periscope telephoto.",
      imageUrl: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=800&auto=format&fit=crop&q=80",
      isFeatured: true,
      isBestseller: true,
      isGamingDeal: false,
      isNewArrival: true,
      specs: JSON.stringify({ "Processor": "Qualcomm Snapdragon 8 Gen 3", "Display": "6.82-inch 2K 120Hz ProXDR AMOLED (4500 nits peak)", "RAM / ROM": "16GB LPDDR5X / 512GB UFS 4.0", "Battery / Charging": "5400 mAh with 100W Wired + 50W AIRVOOC", "Camera": "50MP Sony LYT-808 + 64MP 3x Periscope + 48MP Ultrawide" }),
    },
    {
      name: "OnePlus Nord 4 5G (12GB RAM, 256GB Storage, Mercurial Silver)",
      slug: "oneplus-nord-4-5g-256gb",
      sku: "JC-OP-NORD4",
      categorySlug: "mobiles",
      brandSlug: "oneplus",
      price: 32999,
      salePrice: 29999,
      stock: 12,
      warranty: "1 Year OnePlus India Warranty",
      shortDesc: "Full Metal Unibody Design, Snapdragon 7+ Gen 3, 5500 mAh Battery with 100W SUPERVOOC, 6 Years Software Support.",
      description: "The only all-metal unibody 5G smartphone in the market with incredible battery life, ultra-fast 100W charging, and 6 years of guaranteed software updates.",
      imageUrl: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=800&auto=format&fit=crop&q=80",
      isFeatured: false,
      isBestseller: true,
      isGamingDeal: false,
      isNewArrival: true,
      specs: JSON.stringify({ "Design": "All-Metal Unibody", "Processor": "Snapdragon 7+ Gen 3", "Display": "6.74-inch 1.5K 120Hz AMOLED", "Battery": "5500 mAh (100W Flash Charge)", "OS Updates": "4 Years Android + 6 Years Security" }),
    },

    // --- 16. SAMSUNG ---
    {
      name: "Samsung Galaxy S24 Ultra 5G (12GB RAM, 256GB, Titanium Gray with S Pen)",
      slug: "samsung-galaxy-s24-ultra-5g",
      sku: "JC-SAM-S24U-01",
      categorySlug: "mobiles",
      brandSlug: "samsung",
      price: 129999,
      salePrice: 119999,
      stock: 6,
      warranty: "1 Year Samsung India Brand Warranty",
      shortDesc: "Galaxy AI, Snapdragon 8 Gen 3 for Galaxy, 200MP ProVisual Camera, Built-in S Pen, Titanium Armor.",
      description: "Welcome to the era of mobile AI. With Galaxy S24 Ultra in your hands, you can unleash whole new levels of creativity and productivity with Live Translate, Note Assist, and Circle to Search.",
      imageUrl: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800&auto=format&fit=crop&q=80",
      isFeatured: true,
      isBestseller: true,
      isGamingDeal: false,
      isNewArrival: false,
      specs: JSON.stringify({ "Processor": "Snapdragon 8 Gen 3 for Galaxy", "Display": "6.8-inch Dynamic AMOLED 2X QHD+ 120Hz Flat Display", "Camera": "200MP Wide + 50MP 5x Optical + 12MP Ultrawide + 10MP 3x Optical", "Build": "Titanium Frame + Corning Gorilla Armor Glass", "Stylus": "Built-in S Pen Included" }),
    },
    {
      name: "Samsung 990 PRO 2TB NVMe M.2 PCIe Gen 4 Internal Solid State Drive (SSD)",
      slug: "samsung-990-pro-2tb-nvme-ssd",
      sku: "JC-SSD-990P-2TB",
      categorySlug: "storage",
      brandSlug: "samsung",
      price: 19990,
      salePrice: 16990,
      stock: 14,
      warranty: "5 Years Samsung Official Warranty",
      shortDesc: "Up to 7,450 MB/s Read, 6,900 MB/s Write speeds, PCIe 4.0 NVMe M.2 2280, Smart Thermal Control.",
      description: "Reach near-max performance with PCIe 4.0 speeds. Smart thermal control delivers top-tier power efficiency for heavy gaming, 3D rendering, and 4K video editing workloads.",
      imageUrl: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop&q=80",
      isFeatured: false,
      isBestseller: true,
      isGamingDeal: true,
      isNewArrival: false,
      specs: JSON.stringify({ "Form Factor": "M.2 (2280)", "Interface": "PCIe Gen 4.0 x4, NVMe 2.0", "Sequential Read": "Up to 7,450 MB/s", "Sequential Write": "Up to 6,900 MB/s", "Endurance (TBW)": "1200 TBW", "Warranty": "5 Years" }),
    },
  ];

  let seededCount = 0;
  for (const p of products) {
    const categoryId = categoryMap.get(p.categorySlug) || categoryMap.get("accessories");
    const brandId = p.brandSlug ? brandMap.get(p.brandSlug) : null;

    if (!categoryId) continue;

    const prod = await prisma.product.upsert({
      where: { slug: p.slug },
      update: {
        name: p.name,
        sku: p.sku,
        price: p.price,
        salePrice: p.salePrice || null,
        stock: p.stock,
        inStock: true,
        warranty: p.warranty,
        shortDesc: p.shortDesc,
        description: p.description,
        categoryId: categoryId,
        brandId: brandId || null,
        isFeatured: p.isFeatured,
        isBestseller: p.isBestseller,
        isNewArrival: p.isNewArrival,
        isGamingDeal: p.isGamingDeal || false,
        specsJson: p.specs || null,
      },
      create: {
        name: p.name,
        slug: p.slug,
        sku: p.sku,
        price: p.price,
        salePrice: p.salePrice || null,
        stock: p.stock,
        inStock: true,
        warranty: p.warranty,
        shortDesc: p.shortDesc,
        description: p.description,
        categoryId: categoryId,
        brandId: brandId || null,
        isFeatured: p.isFeatured,
        isBestseller: p.isBestseller,
        isNewArrival: p.isNewArrival,
        isGamingDeal: p.isGamingDeal || false,
        specsJson: p.specs || null,
      },
    });

    // Ensure primary product image exists
    const existingImage = await prisma.productImage.findFirst({
      where: { productId: prod.id },
    });

    if (!existingImage) {
      await prisma.productImage.create({
        data: {
          productId: prod.id,
          url: p.imageUrl,
          isPrimary: true,
          order: 0,
        },
      });
    }

    seededCount++;
  }

  console.log(`✅ Successfully seeded ${seededCount} official products for all 16 brands!`);
  return { success: true, count: seededCount };
}

// Direct execution
if (require.main === module) {
  seedBrandProducts()
    .catch((e) => {
      console.error("Error seeding brand products:", e);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
